#!/bin/bash -eux
echo "SMTP_Host=${MAIL_HOST}" > .env
echo "SMTP_Port=${MAIL_PORT}" >> .env
echo "SMTP_Username=${MAIL_USER}" >> .env
echo "MAIL_Password=${MAIL_PASS}" >> .env
echo "From_Email=${MAIL_USER}" >> .env
echo "MAIL_URL=smtp://${MAIL_USER}:${MAIL_PASS}@${MAIL_HOST}:${MAIL_PORT}/" >> .env
echo "SUBNET=${SUBNET}" >> .env
